CREATE OR REPLACE TRIGGER TRG_S_DESC BEFORE
 INSERT ON AUX_S_DESC FOR EACH ROW DECLARE
 X INTEGER;
 y INTEGER;
 Q INTEGER;
BEGIN
IF :new.ID IS NULL THEN
  SELECT SEQ_S_DESC.NEXTVAL INTO y FROM DUAL;
  :new.ID := y;
 END IF;
END;
 
  /
