connect / as sysdba
alter PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME UNLIMITED;
CREATE USER PROD
IDENTIFIED BY PROD
DEFAULT TABLESPACE PRODUCTION
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED on PRODUCTION;
GRANT create session, create table TO PROD;
CREATE USER TREND
IDENTIFIED BY TREND
DEFAULT TABLESPACE TREND_DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED on TREND_DATA;
GRANT create session, create table TO TREND;
CREATE USER YIELD
IDENTIFIED BY YIELD
DEFAULT TABLESPACE YIELD_DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED on YIELD_DATA;
GRANT create session, create table TO YIELD;
CREATE USER SN6
IDENTIFIED BY SN6
DEFAULT TABLESPACE SN6_DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED on SN6_DATA;
GRANT create session, create table TO SN6;
CREATE USER SU
IDENTIFIED BY SU
DEFAULT TABLESPACE SU_DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED on SU_DATA;
GRANT create session, create table TO SU;
CREATE USER SUS
IDENTIFIED BY SUS
DEFAULT TABLESPACE SUS_DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED on SUS_DATA;
GRANT create session, create table TO SUS;
CREATE USER SUSP
IDENTIFIED BY SUSP
DEFAULT TABLESPACE SUSP_DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED on SUSP_DATA;
GRANT create session, create table TO SUSP;
CREATE USER SLV
IDENTIFIED BY SLV
DEFAULT TABLESPACE SLV_DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED on SLV_DATA;
GRANT create session, create table TO SLV;
CREATE USER MSA
IDENTIFIED BY MSA
DEFAULT TABLESPACE MSA_DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED on MSA_DATA;
GRANT create session, create table TO MSA;
CREATE USER MST
IDENTIFIED BY MST
DEFAULT TABLESPACE MST_DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED on MST_DATA;
GRANT create session, create table TO MST;
CREATE USER ICU
IDENTIFIED BY ICU
DEFAULT TABLESPACE ICU_DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED on ICU_DATA;
GRANT create session, create table TO ICU;
CREATE USER STP
IDENTIFIED BY STP
DEFAULT TABLESPACE STP_DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED on STP_DATA;
GRANT create session, create table TO STP;
CREATE USER XXN
IDENTIFIED BY XXN
DEFAULT TABLESPACE XXN_DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED on XXN_DATA;
GRANT create session, create table TO XXN;
CREATE USER MLC
IDENTIFIED BY MLC
DEFAULT TABLESPACE MLC_DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED on MLC_DATA;
GRANT create session, create table TO MLC;
CREATE USER 
IDENTIFIED BY 
DEFAULT TABLESPACE 
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED on ;
GRANT create session, create table TO ;
CREATE USER VUMADMIN
IDENTIFIED BY VUMADMIN
DEFAULT TABLESPACE VUMADMIN_DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED on VUMADMIN_DATA;
GRANT create session, create table TO VUMADMIN;
quit
