CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."ACCEPT"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."ALBERT"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."APPROVE_SEQ"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."CH3_MULTI_STAT"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."CH3_RMS_RES"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."CH3_STAT"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."CONTAINERDEF"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."CONTAINERFILE"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."CUSTOMER"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."EPCONF_CABLELEN"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."EPCONF_DATA"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."EPCONF_DEF"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."EPCONF_DEF_NEW"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."EPCONF_REV"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."EX"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."EXCEPTIONS"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."FILE_TABLE"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."FLAG"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."FW_OPTION"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."HYD_DATA"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."HYD_DEF"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."HYD_SN"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."JIG"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."JIGG"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."JIG_CONTROL"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."LINK"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."MACRO_JIGSPOT"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."MACRO_JIGSPOT_TEMP"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."MYSITE"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."OPERATOR"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."PASSWORD"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."PASSWORDS"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."PLAN_TABLE"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."P_APPRSEQ"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."P_APPRSEQ_DEF"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."P_APPRSEQ_OPTION"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."P_MACRODEF"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."P_MACRODEFAULT"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."P_MACROEVENT"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."P_MACROFILE"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."P_REV"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."P_SITE"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."P_SPECDEF"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."P_SPECEVENT"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."P_SPECFILE"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."P_SPECLABEL"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."P_SUBTYPE"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."P_SUBTYPE_SEQ"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."P_TESTMODE"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."P_UUT"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."P_VALID_VERSION"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."P_WORKORDER"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."QSNM_BOOT"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."QSNM_SW"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."REPETST"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."REVISION"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."RXPAHSE_FI"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."RXPHASE"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."SECTION_REVS"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."SEQ_TYPE"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."SERIALNO"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."SHUTDOWN"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."SINGLETEST"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."SNM_BOOT"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."SNM_SW"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."SN_DUMP"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."SONC_REV"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."SPECDEF_COMPARE"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."SPECINFO"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."SPECTYPE"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."SPECUSED"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."SPS_SERIAL"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."SPS_VERSION_LAM"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."SW_VERSION"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."SW_VERSION_FILE"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."TULL"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."TULL_DNS"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."VERSION"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."VERSION_CTRL"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."VERSION_FILE"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."YIELDMACRO"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."YIELDSINGLE"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."YIELDXREF"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."YIELDXREFMAIN"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG 
    ON "PROD"."YIELD_SERIALNO"
TABLESPACE "PRODUCTION"
WITH PRIMARY KEY
EXCLUDING NEW VALUES;
